name: user_panel
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  get_it: ^8.0.3
  get: 4.6.6
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  image_picker: ^1.1.2
  hive_flutter: ^1.1.0
  loading_animation_widget: ^1.3.0
  path_provider: ^2.1.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  
